Vagrant.configure("2") do |o|
  # LOAD CONFIG
  # ===========
  # config_json = JSON.parse(File.read("config.json"))
  # @db_name = config_json["db"]["name"]
  # @db_pass = config_json["db"]["root_password"]

  o.vm.box = "ubuntu/trusty64"
  o.vm.network :private_network, ip: "192.168.44.44"

  # SYNC FOLDER
  # ===========
  o.vm.synced_folder "../code/", "/apps", create:true, owner: "vagrant", group: "vagrant"



  # PROVISIONING
  # ============
  o.vm.provision :shell, :path => "./provision-trusty64.sh", :privileged => false
end
